[package]
name = "wb_sqlite"
version = "0.1.0"
authors = ["Werner Braun <wbcat@braun-echle.de>"]
edition = "2021"
#rust-version = "1.78"
description = "Derive macros map struct/field to SQLite table/column, const/fn for create-table,insert,select,update."
repository = "https://github.com/wbcat/wb_sqlite"
license = "MIT OR Apache-2.0"
keywords = ["derive", "sqlite", "database", "orm"]
categories = ["database"]

[lib]
proc-macro = true

[dependencies]
convert_case = "0.6.0"
virtue = "0.0.16"

[dev-dependencies]
# sqlx 0.7.4 needs rusqlite 0.30.0
rusqlite = { version = "0.30.0", features = ["bundled"] }
sqlx = { version = "0.7.4", features = ["sqlite", "runtime-tokio"] }
tokio = { version = "1.38.0", features = ["rt", "macros"] }
