# Rust 1.84
# https://crates.io/crates/cargo-cranky
# https://doc.rust-lang.org/rustc/lints/listing/allowed-by-default.html
# https://rust-lang.github.io/rust-clippy/master/

warn = [
	# rustc
	"explicit_outlives_requirements",
	"ffi_unwind_calls",
	"keyword_idents_2024",
	"let_underscore_drop",
	"macro_use_extern_crate",
	"meta_variable_misuse",
	"missing_abi",
	"non_ascii_idents",
	"non_local_definitions",
	"redundant_lifetimes",
	"single_use_lifetimes",
	"trivial_casts",
	"trivial_numeric_casts",
	"unit_bindings",
	"unnameable_types",
	"unreachable_pub",
	"unsafe_code",
	"unused_crate_dependencies",
	"unused_import_braces",
	"unused_lifetimes",
	"unused_macro_rules",
	"unused_qualifications",
	"variant_size_differences",
	# clippy
	"clippy::allow_attributes_without_reason",
	"clippy::as_ptr_cast_mut",
	"clippy::as_underscore",
	"clippy::assertions_on_result_states",
	"clippy::assigning_clones",
	"clippy::bool_to_int_with_if",
	"clippy::borrow_as_ptr",
	"clippy::branches_sharing_code",
	"clippy::cast_lossless",
	"clippy::cfg_not_test",
	"clippy::clear_with_drain",
	"clippy::clone_on_ref_ptr",
	"clippy::cloned_instead_of_copied",
	"clippy::cognitive_complexity",
	"clippy::collection_is_never_read",
	"clippy::copy_iterator",
	"clippy::debug_assert_with_mut_call",
	"clippy::default_trait_access",
	"clippy::deref_by_slicing",
	"clippy::derive_partial_eq_without_eq",
	"clippy::disallowed_script_idents",
	"clippy::doc_link_with_quotes",
	"clippy::empty_drop",
	"clippy::empty_enum_variants_with_brackets",
	"clippy::empty_line_after_doc_comments",
	"clippy::empty_line_after_outer_attr",
	"clippy::empty_structs_with_brackets",
	"clippy::enum_glob_use",
	"clippy::equatable_if_let",
	"clippy::error_impl_error",
	"clippy::exit",
	"clippy::expl_impl_clone_on_copy",
	"clippy::explicit_deref_methods",
	"clippy::explicit_into_iter_loop",
	"clippy::explicit_iter_loop",
	"clippy::fallible_impl_from",
	"clippy::filter_map_next",
	"clippy::flat_map_option",
	"clippy::float_cmp",
	"clippy::float_cmp_const",
	"clippy::fn_params_excessive_bools",
	"clippy::fn_to_numeric_cast_any",
	"clippy::from_iter_instead_of_collect",
	"clippy::get_unwrap",
	"clippy::if_not_else",
	"clippy::if_then_some_else_none",
	"clippy::ignored_unit_patterns",
	"clippy::implicit_clone",
	"clippy::imprecise_flops",
	"clippy::inconsistent_struct_constructor",
	"clippy::index_refutable_slice",
	"clippy::inefficient_to_string",
	"clippy::infinite_loop",
	"clippy::invalid_upcast_comparisons",
	"clippy::iter_filter_is_ok",
	"clippy::iter_filter_is_some",
	"clippy::iter_not_returning_iterator",
	"clippy::iter_on_empty_collections",
	"clippy::iter_on_single_items",
	"clippy::iter_over_hash_type",
	"clippy::iter_with_drain",
	"clippy::large_digit_groups",
	"clippy::large_futures",
	"clippy::large_stack_arrays",
	"clippy::large_stack_frames",
	"clippy::large_types_passed_by_value",
	"clippy::let_underscore_must_use",
	"clippy::let_underscore_untyped",
	"clippy::lossy_float_literal",
	"clippy::macro_use_imports",
	"clippy::manual_assert",
	"clippy::manual_c_str_literals",
	"clippy::manual_instant_elapsed",
	"clippy::manual_is_power_of_two",
	"clippy::manual_is_variant_and",
	"clippy::manual_let_else",
	"clippy::manual_ok_or",
	"clippy::manual_string_new",
	"clippy::many_single_char_names",
	"clippy::map_err_ignore",
	"clippy::map_unwrap_or",
	"clippy::map_with_unused_argument_over_ranges",
	"clippy::match_bool",
	"clippy::match_same_arms",
	"clippy::match_wild_err_arm",
	"clippy::match_wildcard_for_single_variants",
	"clippy::mem_forget",
	"clippy::mismatching_type_param_order",
	"clippy::missing_asserts_for_indexing",
	"clippy::mixed_read_write_in_expression",
	"clippy::mod_module_files",
	"clippy::multiple_inherent_impl",
	"clippy::mut_mut",
	"clippy::mutex_atomic",
	"clippy::mutex_integer",
	"clippy::naive_bytecount",
	"clippy::needless_bitwise_bool",
	"clippy::needless_collect",
	"clippy::needless_continue",
	"clippy::needless_for_each",
	"clippy::needless_pass_by_ref_mut",
	"clippy::needless_raw_string_hashes",
	"clippy::needless_raw_strings",
	"clippy::negative_feature_names",
	"clippy::non_zero_suggestions",
	"clippy::nonstandard_macro_braces",
	"clippy::option_as_ref_cloned",
	"clippy::option_if_let_else",
	"clippy::option_option",
	"clippy::path_buf_push_overwrite",
	"clippy::pathbuf_init_then_push",
	"clippy::ptr_as_ptr",
	"clippy::ptr_cast_constness",
	"clippy::pub_underscore_fields",
	"clippy::range_minus_one",
	"clippy::range_plus_one",
	"clippy::rc_buffer",
	"clippy::rc_mutex",
	"clippy::redundant_clone",
	"clippy::redundant_closure_for_method_calls",
	"clippy::redundant_feature_names",
	"clippy::redundant_type_annotations",
	"clippy::ref_as_ptr",
	"clippy::ref_binding_to_reference",
	"clippy::ref_option",
	"clippy::ref_option_ref",
	"clippy::ref_patterns",
	"clippy::rest_pat_in_fully_bound_structs",
	"clippy::same_functions_in_if_condition",
	"clippy::same_name_method",
	"clippy::set_contains_or_insert",
	"clippy::single_char_pattern",
	"clippy::single_match_else",
	"clippy::str_split_at_newline",
	"clippy::str_to_string",
	"clippy::string_lit_as_bytes",
	"clippy::string_to_string",
	"clippy::struct_field_names",
	"clippy::suboptimal_flops",
	"clippy::suspicious_operation_groupings",
	"clippy::suspicious_xor_used_as_pow",
	"clippy::tests_outside_test_module",
	"clippy::too_long_first_doc_paragraph",
	"clippy::trailing_empty_array",
	"clippy::trait_duplication_in_bounds",
	"clippy::transmute_ptr_to_ptr",
	"clippy::transmute_undefined_repr",
	"clippy::trivial_regex",
	"clippy::trivially_copy_pass_by_ref",
	"clippy::try_err",
	"clippy::type_repetition_in_bounds",
	"clippy::undocumented_unsafe_blocks",
	"clippy::unicode_not_nfc",
	"clippy::uninhabited_references",
	"clippy::uninlined_format_args",
	"clippy::unnecessary_box_returns",
	"clippy::unnecessary_join",
	"clippy::unnecessary_literal_bound",
	"clippy::unnecessary_self_imports",
	"clippy::unnecessary_struct_initialization",
	"clippy::unnecessary_wraps",
	"clippy::unneeded_field_pattern",
	"clippy::unnested_or_patterns",
	"clippy::unreadable_literal",
	"clippy::unseparated_literal_suffix",
	"clippy::unused_peekable",
	"clippy::unused_result_ok",
	"clippy::unused_rounding",
	"clippy::unused_self",
	"clippy::use_self",
	"clippy::used_underscore_binding",
	"clippy::used_underscore_items",
	"clippy::useless_let_if_seq",
	"clippy::verbose_file_reads",
	"clippy::while_float",
	"clippy::wildcard_dependencies",
	"clippy::wildcard_imports",
	"clippy::zero_sized_map_values",
]
