# Build Time Environment Variables
[env]
# libsqlite3-sys build.rs
LIBSQLITE3_FLAGS = "SQLITE_DQS=0 SQLITE_DEFAULT_MEMSTATUS=0 SQLITE_DEFAULT_WAL_SYNCHRONOUS=1 SQLITE_LIKE_DOESNT_MATCH_BLOBS SQLITE_MAX_EXPR_DEPTH=0"
